// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8qBg2iY-JLin0NX9gvMT2qyrPMxzRlF0',
    appId: '1:265975639920:web:d0a20d527ff2bb663069b5',
    messagingSenderId: '265975639920',
    projectId: 'proplanet-5987f',
    authDomain: 'proplanet-5987f.firebaseapp.com',
    storageBucket: 'proplanet-5987f.firebasestorage.app',
    measurementId: 'G-BLLVN1HY00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPf0HJjBBPp44y9twULm6sW7T1yiRrR4',
    appId: '1:265975639920:android:0a1507f8621f4dab3069b5',
    messagingSenderId: '265975639920',
    projectId: 'proplanet-5987f',
    storageBucket: 'proplanet-5987f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXBqL7ez1H_UgNcx-xuCglpyjiaymS6vg',
    appId: '1:265975639920:ios:cd21bbddb17ff97a3069b5',
    messagingSenderId: '265975639920',
    projectId: 'proplanet-5987f',
    storageBucket: 'proplanet-5987f.firebasestorage.app',
    iosBundleId: 'com.example.proplanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXBqL7ez1H_UgNcx-xuCglpyjiaymS6vg',
    appId: '1:265975639920:ios:cd21bbddb17ff97a3069b5',
    messagingSenderId: '265975639920',
    projectId: 'proplanet-5987f',
    storageBucket: 'proplanet-5987f.firebasestorage.app',
    iosBundleId: 'com.example.proplanet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8qBg2iY-JLin0NX9gvMT2qyrPMxzRlF0',
    appId: '1:265975639920:web:63a3d62b67f54a6f3069b5',
    messagingSenderId: '265975639920',
    projectId: 'proplanet-5987f',
    authDomain: 'proplanet-5987f.firebaseapp.com',
    storageBucket: 'proplanet-5987f.firebasestorage.app',
    measurementId: 'G-23G8DZC73X',
  );
}
